-- ============================================================================
-- TrainHub Database Initialization Script
-- ============================================================================
-- Este script crea la base de datos, usuarios, tablas, índices, constraints,
-- triggers y vistas necesarias para el sistema TrainHub.
--
-- Uso:
--   docker exec -it trainhub-postgres-1 psql -U postgres
--   docker exec -i trainhub-postgres-1 psql -U postgres -d postgres < ./init.sql
-- ============================================================================

-- ============================================================================
-- 1. CREACIÓN DE BASE DE DATOS Y USUARIOS
-- ============================================================================

CREATE DATABASE trainhub_dev_db OWNER postgres;

CREATE ROLE dev_user WITH LOGIN PASSWORD 'dev_pass';

-- Conectarse a la base antes de dar permisos de esquema
\connect trainhub_dev_db

-- Permisos sobre el esquema público
GRANT USAGE, CREATE ON SCHEMA public TO dev_user;

-- Permisos sobre las tablas y secuencias existentes
GRANT SELECT, INSERT, UPDATE, DELETE ON ALL TABLES IN SCHEMA public TO dev_user;
GRANT USAGE, SELECT, UPDATE ON ALL SEQUENCES IN SCHEMA public TO dev_user;

-- Para que las tablas que se crean después también hereden permisos automáticamente
ALTER DEFAULT PRIVILEGES IN SCHEMA public
GRANT SELECT, INSERT, UPDATE, DELETE ON TABLES TO dev_user;
ALTER DEFAULT PRIVILEGES IN SCHEMA public
GRANT USAGE, SELECT, UPDATE ON SEQUENCES TO dev_user;

-- Ajustar el search_path (para que use 'public' por defecto)
ALTER ROLE dev_user SET search_path TO public;

-- ============================================================================
-- 2. CREACIÓN DE TIPOS ENUM
-- ============================================================================

CREATE TYPE account_status_enum AS ENUM ('PENDING_CONFIRMATION', 'ACTIVE', 'BLOCKED');
CREATE TYPE friendship_status_enum AS ENUM ('PENDING', 'FRIEND', 'BLOCKED');
CREATE TYPE message_status_enum AS ENUM ('SENDING', 'SENT', 'DELIVERED', 'READ');

-- ============================================================================
-- 3. CREACIÓN DE TABLAS
-- ============================================================================

-- Tabla: users
CREATE TABLE "users" (
  "id" INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "name" VARCHAR(60) NOT NULL,
  "email" VARCHAR(255) UNIQUE NOT NULL,
  "password_hash" VARCHAR(255) NOT NULL,
  "bio" TEXT,
  "photo_url" VARCHAR(255),
  "account_status" account_status_enum NOT NULL,
  "email_verified" BOOLEAN DEFAULT false,
  "registration_date" TIMESTAMP DEFAULT (now()),
  "last_login" TIMESTAMP,
  -- Constraints de validación
  CONSTRAINT chk_users_name_length CHECK (LENGTH("name") >= 2 AND LENGTH("name") <= 60),
  CONSTRAINT chk_users_bio_length CHECK ("bio" IS NULL OR LENGTH("bio") <= 280),
  CONSTRAINT chk_users_account_status CHECK ("account_status" IN ('PENDING_CONFIRMATION', 'ACTIVE', 'BLOCKED'))
);

-- Tabla: Refresh_Tokens
CREATE TABLE "Refresh_Tokens" (
  "token_hash" VARCHAR(255) PRIMARY KEY,
  "user_id" INT NOT NULL,
  "expiration_date" TIMESTAMP NOT NULL,
  "revoked" BOOLEAN DEFAULT false,
  "creation_date" TIMESTAMP DEFAULT (now())
);

-- Tabla: posts
CREATE TABLE "posts" (
  "id" INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "user_id" INT NOT NULL,
  "r1_time" VARCHAR(5) NOT NULL,
  "r2_time" VARCHAR(5) NOT NULL,
  "r3_time" VARCHAR(5) NOT NULL,
  "r4_time" VARCHAR(5) NOT NULL,
  "r5_time" VARCHAR(5) NOT NULL,
  "r6_time" VARCHAR(5) NOT NULL,
  "r7_time" VARCHAR(5) NOT NULL,
  "r8_time" VARCHAR(5) NOT NULL,
  "w1_time" VARCHAR(5) NOT NULL,
  "w2_time" VARCHAR(5) NOT NULL,
  "w3_time" VARCHAR(5) NOT NULL,
  "w4_time" VARCHAR(5) NOT NULL,
  "w5_time" VARCHAR(5) NOT NULL,
  "w6_time" VARCHAR(5) NOT NULL,
  "w7_time" VARCHAR(5) NOT NULL,
  "w8_time" VARCHAR(5) NOT NULL,
  "total_time" VARCHAR(7) NOT NULL,
  "creation_date" TIMESTAMP NOT NULL DEFAULT (now()),
  -- Constraints de validación
  CONSTRAINT chk_posts_total_time_format CHECK (
    "total_time" ~ '^[0-9]{1,2}:[0-5][0-9]:[0-5][0-9]$' OR
    "total_time" ~ '^[0-9]{1,2}:[0-5][0-9]$'
  )
);

-- Tabla: friendships
CREATE TABLE "friendships" (
  "user_a_id" INT NOT NULL,
  "user_b_id" INT NOT NULL,
  "status" friendship_status_enum NOT NULL,
  "relationship_start_date" TIMESTAMP DEFAULT (now()),
  PRIMARY KEY ("user_a_id", "user_b_id"),
  -- Constraint para garantizar user_a_id < user_b_id (se valida con trigger)
  CONSTRAINT chk_friendships_user_order CHECK ("user_a_id" < "user_b_id")
);

-- Tabla: Likes
CREATE TABLE "Likes" (
  "user_id" INT NOT NULL,
  "post_id" INT NOT NULL,
  "like_date" TIMESTAMP DEFAULT (now()),
  PRIMARY KEY ("user_id", "post_id")
);

-- Tabla: Messages
CREATE TABLE "Messages" (
  "id" INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "sender_id" INT NOT NULL,
  "receiver_id" INT NOT NULL,
  "content" VARCHAR(2000) NOT NULL,
  "send_date" TIMESTAMP DEFAULT (now()),
  "read_at" TIMESTAMP DEFAULT (now()),
  "status" message_status_enum NOT NULL,
  -- Constraints de validación
  CONSTRAINT chk_messages_sender_receiver CHECK ("sender_id" != "receiver_id"),
  CONSTRAINT chk_messages_content_not_empty CHECK (LENGTH(TRIM("content")) > 0)
);

-- ============================================================================
-- 4. FOREIGN KEYS CON ON DELETE
-- ============================================================================

ALTER TABLE "Refresh_Tokens" 
  ADD CONSTRAINT fk_refresh_tokens_user_id 
  FOREIGN KEY ("user_id") REFERENCES "users" ("id") 
  ON DELETE CASCADE;

ALTER TABLE "posts" 
  ADD CONSTRAINT fk_posts_user_id 
  FOREIGN KEY ("user_id") REFERENCES "users" ("id") 
  ON DELETE CASCADE;

ALTER TABLE "friendships" 
  ADD CONSTRAINT fk_friendships_user_a_id 
  FOREIGN KEY ("user_a_id") REFERENCES "users" ("id") 
  ON DELETE CASCADE;

ALTER TABLE "friendships" 
  ADD CONSTRAINT fk_friendships_user_b_id 
  FOREIGN KEY ("user_b_id") REFERENCES "users" ("id") 
  ON DELETE CASCADE;

ALTER TABLE "Likes" 
  ADD CONSTRAINT fk_likes_user_id 
  FOREIGN KEY ("user_id") REFERENCES "users" ("id") 
  ON DELETE CASCADE;

ALTER TABLE "Likes" 
  ADD CONSTRAINT fk_likes_post_id 
  FOREIGN KEY ("post_id") REFERENCES "posts" ("id") 
  ON DELETE CASCADE;

ALTER TABLE "Messages" 
  ADD CONSTRAINT fk_messages_sender_id 
  FOREIGN KEY ("sender_id") REFERENCES "users" ("id") 
  ON DELETE CASCADE;

ALTER TABLE "Messages" 
  ADD CONSTRAINT fk_messages_receiver_id 
  FOREIGN KEY ("receiver_id") REFERENCES "users" ("id") 
  ON DELETE CASCADE;

-- ============================================================================
-- 5. ÍNDICES CRÍTICOS (Alta Prioridad)
-- ============================================================================

-- users
CREATE INDEX "idx_users_username" ON "users" ("name");

-- Refresh_Tokens
CREATE INDEX "idx_refresh_tokens_user_id" ON "Refresh_Tokens" ("user_id");
CREATE INDEX "idx_refresh_tokens_expiration_date" ON "Refresh_Tokens" ("expiration_date");

-- posts
CREATE INDEX "idx_posts_user_id" ON "posts" ("user_id");
CREATE INDEX "idx_posts_creation_date" ON "posts" ("creation_date" DESC);

-- friendships
CREATE INDEX "idx_friendships_user_a" ON "friendships" ("user_a_id");
CREATE INDEX "idx_friendships_user_b" ON "friendships" ("user_b_id");

-- Likes
CREATE INDEX "idx_likes_post_id" ON "Likes" ("post_id");

-- Messages
CREATE INDEX "idx_messages_sender_id" ON "Messages" ("sender_id");
CREATE INDEX "idx_messages_receiver_id" ON "Messages" ("receiver_id");
CREATE INDEX "idx_messages_send_date" ON "Messages" ("send_date" DESC);

-- ============================================================================
-- 6. ÍNDICES COMPUESTOS (Alta Prioridad)
-- ============================================================================

-- posts: Para feed optimizado (filtra por user_id y ordena por creation_date)
CREATE INDEX "idx_posts_user_creation" ON "posts" ("user_id", "creation_date" DESC);

-- friendships: Para filtrar amigos eficientemente
CREATE INDEX "idx_friendships_user_a_status" ON "friendships" ("user_a_id", "status");
CREATE INDEX "idx_friendships_user_b_status" ON "friendships" ("user_b_id", "status");

-- Messages: Para conversaciones bidireccionales optimizadas
CREATE INDEX "idx_messages_sender_receiver_date" ON "Messages" ("sender_id", "receiver_id", "send_date" DESC);
CREATE INDEX "idx_messages_receiver_sender_date" ON "Messages" ("receiver_id", "sender_id", "send_date" DESC);

-- ============================================================================
-- 7. TRIGGERS
-- ============================================================================

-- Trigger: Validar y normalizar user_a_id < user_b_id en friendships
CREATE OR REPLACE FUNCTION validate_friendship_order()
RETURNS TRIGGER AS $$
BEGIN
  -- Si user_a_id > user_b_id, intercambiar valores
  IF NEW."user_a_id" > NEW."user_b_id" THEN
    DECLARE
      temp_id INT;
    BEGIN
      temp_id := NEW."user_a_id";
      NEW."user_a_id" := NEW."user_b_id";
      NEW."user_b_id" := temp_id;
    END;
  END IF;
  RETURN NEW;
END;
$$ LANGUAGE plpgsql;

CREATE TRIGGER trg_friendships_validate_order
  BEFORE INSERT OR UPDATE ON "friendships"
  FOR EACH ROW
  EXECUTE FUNCTION validate_friendship_order();

-- Trigger: Actualizar read_at cuando status cambia a READ
CREATE OR REPLACE FUNCTION update_message_read_at()
RETURNS TRIGGER AS $$
BEGIN
  IF NEW."status" = 'READ' AND (OLD."status" IS NULL OR OLD."status" != 'READ') THEN
    NEW."read_at" := NOW();
  END IF;
  RETURN NEW;
END;
$$ LANGUAGE plpgsql;

CREATE TRIGGER trg_messages_update_read_at
  BEFORE UPDATE ON "Messages"
  FOR EACH ROW
  EXECUTE FUNCTION update_message_read_at();

-- ============================================================================
-- 8. VISTAS ÚTILES
-- ============================================================================

-- Vista: Posts con conteo de likes
CREATE OR REPLACE VIEW "posts_with_likes" AS
SELECT 
  p.*,
  COALESCE(COUNT(l."post_id"), 0) AS likes_count
FROM "posts" p
LEFT JOIN "Likes" l ON p."id" = l."post_id"
GROUP BY p."id";

-- Vista: Conversaciones con último mensaje (adaptada a estructura sin tabla Conversations)
-- Esta vista agrupa mensajes por pares de usuarios y muestra el último mensaje de cada conversación
CREATE OR REPLACE VIEW "conversations_summary" AS
WITH normalized_conversations AS (
  SELECT 
    CASE 
      WHEN "sender_id" < "receiver_id" 
      THEN "sender_id"
      ELSE "receiver_id"
    END AS "user_a_id",
    CASE 
      WHEN "sender_id" < "receiver_id" 
      THEN "receiver_id"
      ELSE "sender_id"
    END AS "user_b_id",
    "id",
    "content",
    "send_date",
    "status",
    "sender_id",
    "receiver_id",
    ROW_NUMBER() OVER (
      PARTITION BY 
        CASE 
          WHEN "sender_id" < "receiver_id" 
          THEN ("sender_id", "receiver_id")
          ELSE ("receiver_id", "sender_id")
        END
      ORDER BY "send_date" DESC
    ) AS rn
  FROM "Messages"
)
SELECT 
  "user_a_id",
  "user_b_id",
  "id" AS "last_message_id",
  "content" AS "last_message_content",
  "send_date" AS "last_message_date",
  "status" AS "last_message_status",
  "sender_id" AS "last_message_sender_id",
  "receiver_id" AS "last_message_receiver_id"
FROM normalized_conversations
WHERE rn = 1;

-- ============================================================================
-- FIN DEL SCRIPT
-- ============================================================================
