-- DB Diagram: https://dbdiagram.io/d/69305deed6676488ba746f1d

CREATE TABLE "users" (
  "id" INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "email" varchar(255) UNIQUE NOT NULL,
  "username" varchar(50) UNIQUE NOT NULL,
  "password_hash" varchar(255) NOT NULL,
  "photo_url" varchar(255),
  "account_status" varchar(50) NOT NULL CHECK (account_status IN ('PENDING_CONFIRMATION', 'ACTIVE', 'BLOCKED')),
  "email_verified" boolean DEFAULT false,
  "email_confirmation_token" varchar(255),
  "password_reset_token" varchar(255),
  "password_reset_expires_at" TIMESTAMP WITH TIME ZONE
);


CREATE TABLE "posts" (
  "id" INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "user_id" int NOT NULL,
  "r1_time" int NOT NULL,
  "r2_time" int NOT NULL,
  "r3_time" int NOT NULL,
  "r4_time" int NOT NULL,
  "r5_time" int NOT NULL,
  "r6_time" int NOT NULL,
  "r7_time" int NOT NULL, 
  "r8_time" int NOT NULL,
  "w1_time" int NOT NULL,
  "w2_time" int NOT NULL,
  "w3_time" int NOT NULL,
  "w4_time" int NOT NULL,
  "w5_time" int NOT NULL,
  "w6_time" int NOT NULL,
  "w7_time" int NOT NULL,
  "w8_time" int NOT NULL,
  "total_time" int NOT NULL,
  "creation_date" timestamp NOT NULL DEFAULT (now()),
  CONSTRAINT "fk_posts_users" FOREIGN KEY ("user_id") REFERENCES "users" ("id")
);


-- unsa sola fila por pareja
CREATE TABLE "friendships" (
  "user_a_id" int NOT NULL,
  "user_b_id" int NOT NULL,
  "status" varchar(50) NOT NULL CHECK (status IN ('PENDING', 'FRIEND')),
  PRIMARY KEY (user_a_id,user_b_id),
  CONSTRAINT "chk_friendships_user_order" CHECK ("user_a_id" < "user_b_id"),
  CONSTRAINT "fk_friendships_users_a" FOREIGN KEY ("user_a_id") REFERENCES "users" ("id"),
  CONSTRAINT "fk_friendships_users_b" FOREIGN KEY ("user_b_id") REFERENCES "users" ("id")
);

