-- DB Diagram: https://dbdiagram.io/d/69305deed6676488ba746f1d

-- Dar permisos en el esquema public (necesario para crear tablas)
GRANT ALL ON SCHEMA public TO dev_user;
ALTER DEFAULT PRIVILEGES IN SCHEMA public GRANT ALL ON TABLES TO dev_user;
ALTER DEFAULT PRIVILEGES IN SCHEMA public GRANT ALL ON SEQUENCES TO dev_user;

-- Crear esquema (opcional pero clean)
CREATE SCHEMA IF NOT EXISTS app AUTHORIZATION dev_user;

-- Establecer el esquema app como predeterminado para las siguientes operaciones
SET search_path TO app, public;

CREATE TYPE account_status AS ENUM ('PENDING_CONFIRMATION', 'ACTIVE', 'BLOCKED');
CREATE TABLE "users" (
  "id" INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "email" varchar(255) UNIQUE NOT NULL,
  "password_hash" varchar(255) NOT NULL,
  "photo_url" varchar(255),
  "account_status" account_status NOT NULL,
  "email_verified" boolean DEFAULT false,
  "email_confirmation_token" varchar(255)
);



CREATE TABLE "posts" (
  "id" INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "user_id" int NOT NULL,
  "total_time" varchar(7) NOT NULL,
  CONSTRAINT "fk_posts_users" FOREIGN KEY ("user_id") REFERENCES "users" ("id")
);

CREATE TYPE friendship_status AS ENUM ('PENDING', 'FRIEND', 'BLOCKED');

CREATE TABLE "friendships" (
  "user_a_id" int NOT NULL,
  "user_b_id" int NOT NULL,
  "status" friendship_status NOT NULL,
  PRIMARY KEY (user_a_id,user_b_id),
  CONSTRAINT "fk_friendships_users_a" FOREIGN KEY ("user_a_id") REFERENCES "users" ("id"),
  CONSTRAINT "fk_friendships_users_b" FOREIGN KEY ("user_b_id") REFERENCES "users" ("id")
);

