-- DB Diagram: https://dbdiagram.io/d/69305deed6676488ba746f1d


CREATE TABLE "users" (
  "id" INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "email" varchar(255) UNIQUE NOT NULL,
  "username" varchar(50) UNIQUE NOT NULL,
  "password_hash" varchar(255) NOT NULL,
  "photo_url" varchar(255),
  "account_status" varchar(50) NOT NULL CHECK (account_status IN ('PENDING_CONFIRMATION', 'ACTIVE', 'BLOCKED')),
  "email_verified" boolean DEFAULT false,
  "email_confirmation_token" varchar(255),
  "password_reset_token" varchar(255),
  "password_reset_expires_at" TIMESTAMP WITH TIME ZONE,
  "notifications_last_seen_at" TIMESTAMP,
  "gender" varchar(10) CHECK (gender IN ('MALE', 'FEMALE'))
);


CREATE TABLE "posts" (
  "id" INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "user_id" int NOT NULL,
  "running1" int NOT NULL,
  "running2" int NOT NULL,
  "running3" int NOT NULL,
  "running4" int NOT NULL,
  "running5" int NOT NULL,
  "running6" int NOT NULL,
  "running7" int NOT NULL, 
  "running8" int NOT NULL,
  "ski_erg" int NOT NULL,
  "sled_push" int NOT NULL,
  "sled_pull" int NOT NULL,
  "burpee_broad_jump" int NOT NULL,
  "row" int NOT NULL,
  "farmers_carry" int NOT NULL,
  "sandbag_lunges" int NOT NULL,
  "wall_balls" int NOT NULL,
  "total_time" int NOT NULL,
  "description" text,
  "category" varchar(20) NOT NULL DEFAULT 'INDIVIDUAL_MALE',
  "creation_date" timestamp NOT NULL DEFAULT (now()),
  "mate" int,
  CONSTRAINT "fk_posts_users" FOREIGN KEY ("user_id") REFERENCES "users" ("id"),
  CONSTRAINT "fk_posts_mate" FOREIGN KEY ("mate") REFERENCES "users" ("id") ON DELETE SET NULL,
  CONSTRAINT "chk_posts_category" CHECK ("category" IN ('INDIVIDUAL_MALE', 'INDIVIDUAL_FEMALE', 'DOUBLES_MIXED', 'DOUBLES_MALE', 'DOUBLES_FEMALE'))
);



-- unsa sola fila por pareja
CREATE TABLE "friendships" (
  "user_a_id" int NOT NULL,
  "user_b_id" int NOT NULL,
  "status" varchar(50) NOT NULL CHECK (status IN ('PENDING', 'FRIEND')),
  "requester_id" INT NOT NULL,
  "created_at" TIMESTAMP NOT NULL DEFAULT now(),
  "accepted_at" TIMESTAMP,
  PRIMARY KEY (user_a_id,user_b_id),
  CONSTRAINT "chk_friendships_user_order" CHECK ("user_a_id" < "user_b_id"),
  CONSTRAINT "fk_friendships_users_a" FOREIGN KEY ("user_a_id") REFERENCES "users" ("id"),
  CONSTRAINT "fk_friendships_users_b" FOREIGN KEY ("user_b_id") REFERENCES "users" ("id"),
  CONSTRAINT "fk_friendships_requester" FOREIGN KEY ("requester_id") REFERENCES "users" ("id")
);


CREATE TABLE "post_likes" (
  "post_id" int NOT NULL,
  "user_id" int NOT NULL,
  "created_at" timestamp NOT NULL DEFAULT (now()),
  PRIMARY KEY ("post_id", "user_id"),
  CONSTRAINT "fk_post_likes_post" FOREIGN KEY ("post_id") REFERENCES "posts" ("id") ON DELETE CASCADE,
  CONSTRAINT "fk_post_likes_user" FOREIGN KEY ("user_id") REFERENCES "users" ("id") ON DELETE CASCADE
);



  CREATE TABLE "comments" (
  "id" INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "post_id" int NOT NULL,
  "user_id" int NOT NULL,
  "content" text NOT NULL,
  "creation_date" timestamp NOT NULL DEFAULT (now()),
  CONSTRAINT "fk_comments_posts" FOREIGN KEY ("post_id") REFERENCES "posts" ("id") ON DELETE CASCADE,
  CONSTRAINT "fk_comments_users" FOREIGN KEY ("user_id") REFERENCES "users" ("id") ON DELETE CASCADE,
  CONSTRAINT "fk_comments_mate" FOREIGN KEY ("mate") REFERENCES "users" ("id") ON DELETE SET NULL
);

CREATE TABLE "comment_likes" (
  "comment_id" int NOT NULL,
  "user_id" int NOT NULL,
  "created_at" timestamp NOT NULL DEFAULT (now()),
  PRIMARY KEY ("comment_id", "user_id"),
  CONSTRAINT "fk_comment_likes_comment" FOREIGN KEY ("comment_id") REFERENCES "comments" ("id") ON DELETE CASCADE,
  CONSTRAINT "fk_comment_likes_user" FOREIGN KEY ("user_id") REFERENCES "users" ("id") ON DELETE CASCADE
);