CREATE TABLE "users" (
  "id" INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "name" varchar(60) NOT NULL,
  "email" varchar(255) UNIQUE NOT NULL,
  "password_hash" varchar(255) NOT NULL,
  "bio" text,
  "photo_url" varchar(255),
  "account_status" "enum(PENDING_CONFIRMATION,ACTIVE,BLOCKED)" NOT NULL,
  "email_verified" boolean DEFAULT false,
  "registration_date" timestamp DEFAULT (now()),
  "last_login" timestamp
);

CREATE TABLE "Refresh_Tokens" (
  "token_hash" varchar(255) PRIMARY KEY,
  "user_id" int NOT NULL,
  "expiration_date" timestamp NOT NULL,
  "revoked" boolean DEFAULT false,
  "creation_date" timestamp DEFAULT (now())
);

CREATE TABLE "posts" (
  "id" INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "user_id" int NOT NULL,
  "r1_time" varchar(5) NOT NULL,
  "r2_time" varchar(5) NOT NULL,
  "r3_time" varchar(5) NOT NULL,
  "r4_time" varchar(5) NOT NULL,
  "r5_time" varchar(5) NOT NULL,
  "r6_time" varchar(5) NOT NULL,
  "r7_time" varchar(5) NOT NULL,
  "r8_time" varchar(5) NOT NULL,
  "w1_time" varchar(5) NOT NULL,
  "w2_time" varchar(5) NOT NULL,
  "w3_time" varchar(5) NOT NULL,
  "w4_time" varchar(5) NOT NULL,
  "w5_time" varchar(5) NOT NULL,
  "w6_time" varchar(5) NOT NULL,
  "w7_time" varchar(5) NOT NULL,
  "w8_time" varchar(5) NOT NULL,
  "total_time" varchar(7) NOT NULL,
  "creation_date" timestamp NOT NULL DEFAULT (now())
);

CREATE TABLE "friendships" (
  "user_a_id" int NOT NULL,
  "user_b_id" int NOT NULL,
  "status" "enum(PENDING,FRIEND,BLOCKED)" NOT NULL,
  "relationship_start_date" timestamp DEFAULT (now()),
  "Primary" key(user_a_id,user_b_id)
);

CREATE TABLE "Likes" (
  "user_id" int NOT NULL,
  "post_id" int NOT NULL,
  "like_date" timestamp DEFAULT (now()),
  "Primary" key(user_id,post_id)
);

CREATE TABLE "Messages" (
  "id" INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "sender_id" int NOT NULL,
  "receiver_id" int NOT NULL,
  "content" varchar(2000) NOT NULL,
  "send_date" timestamp DEFAULT (now()),
  "read_at" timestamp DEFAULT (now()),
  "status" "enum(SENDING,SENT,DELIVERED,READ)" NOT NULL
);

CREATE INDEX "idx_users_username" ON "users" ("name");

ALTER TABLE "Refresh_Tokens" ADD FOREIGN KEY ("user_id") REFERENCES "users" ("id");

ALTER TABLE "posts" ADD FOREIGN KEY ("user_id") REFERENCES "users" ("id");

ALTER TABLE "friendships" ADD FOREIGN KEY ("user_a_id") REFERENCES "users" ("id");

ALTER TABLE "friendships" ADD FOREIGN KEY ("user_b_id") REFERENCES "users" ("id");

ALTER TABLE "Likes" ADD FOREIGN KEY ("user_id") REFERENCES "users" ("id");

ALTER TABLE "Likes" ADD FOREIGN KEY ("post_id") REFERENCES "posts" ("id");

ALTER TABLE "Messages" ADD FOREIGN KEY ("sender_id") REFERENCES "users" ("id");

ALTER TABLE "Messages" ADD FOREIGN KEY ("receiver_id") REFERENCES "users" ("id");
