-- DB Diagram: https://dbdiagram.io/d/69305deed6676488ba746f1d


CREATE TABLE "cities" (
  "id" INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "name" varchar(100) NOT NULL,
  UNIQUE ("name")
);


CREATE TABLE "boxes" (
  "id" INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "name" varchar(150) NOT NULL,
  "city_id" int NOT NULL,
  "address" varchar(255),
  CONSTRAINT "fk_boxes_city" FOREIGN KEY ("city_id") REFERENCES "cities" ("id")
);


CREATE TABLE "users" (
  "id" INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "email" varchar(255) UNIQUE NOT NULL,
  "username" varchar(50) UNIQUE NOT NULL,
  "password_hash" varchar(255) NOT NULL,
  "photo_url" varchar(255),
  "account_status" varchar(50) NOT NULL CHECK (account_status IN ('PENDING_CONFIRMATION', 'ACTIVE', 'BLOCKED')),
  "email_verified" boolean DEFAULT false,
  "email_confirmation_token" varchar(255),
  "password_reset_token" varchar(255),
  "password_reset_expires_at" TIMESTAMP WITH TIME ZONE,
  "notifications_last_seen_at" TIMESTAMP,
  "gender" varchar(10) CHECK (gender IN ('MALE', 'FEMALE')),
  "role" varchar(20) NOT NULL DEFAULT 'USER' CHECK (role IN ('USER', 'BOX_ADMIN')),
  box_id INT,
  FOREIGN KEY (box_id) REFERENCES boxes(id) ON DELETE SET NULL
);


CREATE TABLE "posts" (
  "id" INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "user_id" int NOT NULL,
  "post_type" varchar(30) NOT NULL,
  "box_id" int,
  "title" varchar(150),
  "training_tag" varchar(20),
  "challenge_deadline" TIMESTAMP WITH TIME ZONE,
  "description" text,
  "creation_date" timestamp NOT NULL DEFAULT (now()),
  "wod_post_id" int,
  CONSTRAINT "fk_posts_users" FOREIGN KEY ("user_id") REFERENCES "users" ("id"),
  CONSTRAINT "fk_posts_box" FOREIGN KEY ("box_id") REFERENCES "boxes" ("id"),
  CONSTRAINT "fk_posts_wod" FOREIGN KEY ("wod_post_id") REFERENCES "posts" ("id") ON DELETE SET NULL,
  CONSTRAINT "chk_posts_post_type" CHECK ("post_type" IN ('CHECKIN', 'BOX_WOD', 'BOX_CHALLENGE', 'BOX_ANNOUNCEMENT'))
);

CREATE INDEX "idx_posts_wod_post_id" ON "posts" ("wod_post_id");
CREATE UNIQUE INDEX "uq_posts_user_wod_checkin" ON "posts" ("user_id", "wod_post_id") WHERE "wod_post_id" IS NOT NULL;


CREATE TABLE "post_participants" (
  "post_id" int NOT NULL,
  "user_id" int NOT NULL,
  "joined_at" timestamp NOT NULL DEFAULT (now()),
  PRIMARY KEY ("post_id", "user_id"),
  CONSTRAINT "fk_post_participants_post" FOREIGN KEY ("post_id") REFERENCES "posts" ("id") ON DELETE CASCADE,
  CONSTRAINT "fk_post_participants_user" FOREIGN KEY ("user_id") REFERENCES "users" ("id") ON DELETE CASCADE
);



-- unsa sola fila por pareja
CREATE TABLE "friendships" (
  "user_a_id" int NOT NULL,
  "user_b_id" int NOT NULL,
  "status" varchar(50) NOT NULL CHECK (status IN ('PENDING', 'FRIEND')),
  "requester_id" INT NOT NULL,
  "created_at" TIMESTAMP NOT NULL DEFAULT now(),
  "accepted_at" TIMESTAMP,
  PRIMARY KEY (user_a_id,user_b_id),
  CONSTRAINT "chk_friendships_user_order" CHECK ("user_a_id" < "user_b_id"),
  CONSTRAINT "fk_friendships_users_a" FOREIGN KEY ("user_a_id") REFERENCES "users" ("id"),
  CONSTRAINT "fk_friendships_users_b" FOREIGN KEY ("user_b_id") REFERENCES "users" ("id"),
  CONSTRAINT "fk_friendships_requester" FOREIGN KEY ("requester_id") REFERENCES "users" ("id")
);


CREATE TABLE "post_likes" (
  "post_id" int NOT NULL,
  "user_id" int NOT NULL,
  "created_at" timestamp NOT NULL DEFAULT (now()),
  PRIMARY KEY ("post_id", "user_id"),
  CONSTRAINT "fk_post_likes_post" FOREIGN KEY ("post_id") REFERENCES "posts" ("id") ON DELETE CASCADE,
  CONSTRAINT "fk_post_likes_user" FOREIGN KEY ("user_id") REFERENCES "users" ("id") ON DELETE CASCADE
);



  CREATE TABLE "comments" (
  "id" INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "post_id" int NOT NULL,
  "user_id" int NOT NULL,
  "content" text NOT NULL,
  "creation_date" timestamp NOT NULL DEFAULT (now()),
  CONSTRAINT "fk_comments_posts" FOREIGN KEY ("post_id") REFERENCES "posts" ("id") ON DELETE CASCADE,
  CONSTRAINT "fk_comments_users" FOREIGN KEY ("user_id") REFERENCES "users" ("id") ON DELETE CASCADE
);

CREATE TABLE "comment_likes" (
  "comment_id" int NOT NULL,
  "user_id" int NOT NULL,
  "created_at" timestamp NOT NULL DEFAULT (now()),
  PRIMARY KEY ("comment_id", "user_id"),
  CONSTRAINT "fk_comment_likes_comment" FOREIGN KEY ("comment_id") REFERENCES "comments" ("id") ON DELETE CASCADE,
  CONSTRAINT "fk_comment_likes_user" FOREIGN KEY ("user_id") REFERENCES "users" ("id") ON DELETE CASCADE
);