spring.application.name=backend

# Configuración de Base de Datos PostgreSQL
    # la base de datos que creamos en el docker-compose.yml
spring.datasource.url=jdbc:postgresql://localhost:5431/trainhub_dev_db
spring.datasource.username=dev_user
spring.datasource.password=dev_pass
spring.datasource.driver-class-name=org.postgresql.Driver

# Configuración de JPA/Hibernate
spring.jpa.hibernate.ddl-auto=validate
# spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect
spring.jpa.properties.hibernate.format_sql=true